apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-sample2
    app.kubernetes.io/part-of: application-sample
  name: component-sample2
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: component-sample2
status:
  loadBalancer: {}
